export type Category = "All" | "Vegetarian" | "Chicken" | "Fish" | "Lamb" | "Dessert";
export type Difficulty = "Easy" | "Medium" | "Hard";

export interface Recipe {
  id: string;
  slug: string;
  title: string;
  category: Exclude<Category, "All">;
  thumbnail: string;
  videoUrl: string;
  videoType: "tiktok" | "instagram" | "youtube";
  shortDescription: string;
  prepTime: string;
  cookTime: string;
  totalTime: string;
  servings: number;
  difficulty: Difficulty;
  ingredients: string[];
  method: string[];
  tips: string[];
  creatorName: string;
  creatorHandle: string;
  relatedRecipes: string[];
  seoTitle: string;
  seoDescription: string;
  calories?: number;
  protein?: number;
  carbs?: number;
  fats?: number;
  fibre?: number;
}

export const recipes: Recipe[] = [
  {
    id: "1",
    slug: "pepes-style-chicken",
    title: "Pepe's Style Chicken & Rice",
    category: "Chicken",
    thumbnail: "/pepes_style_peri_peri_chicken.jpg",
    videoUrl: "https://www.tiktok.com/embed/v2/7637181224842431767",
    videoType: "tiktok",
    shortDescription: "Peri-marinated chicken cubes with spiced biryani rice and a creamy homemade garlic mayo — a Nando's-style fakeaway done right.",
    prepTime: "15 mins",
    cookTime: "20 mins",
    totalTime: "1 hr 35 mins (incl. marinating)",
    servings: 1,
    difficulty: "Easy",
    ingredients: [
      "— Chicken —",
      "1 chicken breast, cut into small cubes",
      "2 tbsp hot peri rub",
      "¾ tsp paprika",
      "¾ tsp salt",
      "2 tbsp peri sauce",
      "1 tbsp mayo",
      "30ml oil",
      "Juice of ¼ lemon",
      "— Rice —",
      "1 cup rice, soaked for 1 hour and washed",
      "¼ packet biryani mix",
      "¾ tsp turmeric",
      "¾ tsp salt",
      "2 cups water",
      "Oil, for the pan",
      "— Garlic Mayo —",
      "200g full-fat mayo",
      "100g yogurt",
      "1 tbsp garlic powder",
      "1 tbsp caster sugar",
      "Splash of water (to preferred consistency)",
    ],
    method: [
      "Mix the peri rub, paprika, salt, peri sauce, mayo, oil and lemon juice together in a bowl. Add the cubed chicken and mix until fully coated.",
      "Cover and place in the fridge to marinate for at least 1 hour.",
      "For the garlic mayo: combine the mayo, yogurt, garlic powder and caster sugar. Add a splash of water and mix until smooth. Set aside.",
      "For the rice: add a little oil to a pan, then add the biryani mix, turmeric and salt. Stir for a few seconds to release the flavour.",
      "Add the washed rice and mix gently so the rice is coated in the spices. Pour in 2 cups of water.",
      "Bring to a boil, then reduce the heat, cover with a lid and cook for 8–10 minutes until the water has absorbed and the rice is cooked.",
      "Turn off the heat and leave the rice to rest with the lid on for a few minutes.",
      "Meanwhile, cook the marinated chicken in a hot oiled pan or grill until charred and cooked through, about 8–10 minutes.",
      "Serve the chicken over the rice with a generous drizzle of garlic mayo.",
    ],
    tips: [
      "The garlic mayo makes more than one serving — store it in a jar in the fridge for up to a week.",
      "The longer you marinate the chicken, the deeper the peri flavour. Overnight is ideal.",
      "For extra char, finish the chicken under a hot grill for 2–3 minutes.",
    ],
    creatorName: "Qia Cooks",
    creatorHandle: "@qiacooks",
    relatedRecipes: ["tandoori-chicken", "bang-bang-chicken-tenders", "korean-style-chicken"],
    seoTitle: "Pepe's Style Chicken & Rice | Curated Recipes",
    seoDescription: "Peri-marinated chicken with spiced biryani rice and homemade garlic mayo — a Nando's-style fakeaway from @qiacooks.",
  },
  {
    id: "2",
    slug: "tandoori-chicken",
    title: "Tandoori Chicken",
    category: "Chicken",
    thumbnail: "/tandoori_chicken.jpg",
    videoUrl: "https://www.tiktok.com/embed/v2/7598936006917672214",
    videoType: "tiktok",
    shortDescription: "A whole chicken marinated overnight in a bold spiced yogurt marinade and air-fried to smoky, charred perfection.",
    prepTime: "15 mins",
    cookTime: "32 mins",
    totalTime: "47 mins (+ overnight marinating)",
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "1 medium whole chicken",
      "4 garlic cloves, minced",
      "Small piece of ginger, grated",
      "1 tbsp paprika",
      "1 tbsp tandoori masala",
      "½ tbsp dried coriander",
      "½ tbsp ground cumin",
      "½ tbsp fenugreek",
      "½ tbsp black pepper",
      "½ tbsp salt",
      "Juice of ½ lemon",
      "60ml oil",
      "Pinch of red food colour (optional)",
    ],
    method: [
      "Combine the garlic, ginger, paprika, tandoori masala, dried coriander, cumin, fenugreek, black pepper, salt, lemon juice, oil and food colour in a bowl. Mix well into a paste.",
      "Score the chicken deeply all over (including the thighs and breast) so the marinade can penetrate.",
      "Coat the chicken thoroughly in the marinade, making sure it gets into all the cuts. Cover and refrigerate overnight (minimum 2 hours).",
      "When ready to cook, preheat the air fryer to 180°C.",
      "Place the chicken breast-side down. Air fry for 16 minutes.",
      "Flip the chicken breast-side up and air fry for a further 16 minutes.",
      "Check the thickest part of the thigh — juices should run clear. Rest for 5–10 minutes before carving.",
    ],
    tips: [
      "Overnight marinating is non-negotiable for the full depth of flavour.",
      "Scoring the chicken deeply lets the spices work all the way to the bone.",
      "Serve with naan, raita and sliced onions with chaat masala.",
    ],
    creatorName: "Qia Cooks",
    creatorHandle: "@qiacooks",
    relatedRecipes: ["pepes-style-chicken", "hyderabadwali-shaadi-chicken", "miso-chicken-and-spinach-rice"],
    seoTitle: "Tandoori Chicken | Curated Recipes",
    seoDescription: "Whole tandoori chicken marinated overnight and air-fried in 32 minutes. Step-by-step written recipe from @qiacooks on TikTok.",
  },
  {
    id: "3",
    slug: "hyderabadwali-shaadi-chicken",
    title: "Hyderabadwali Shaadi Chicken",
    category: "Chicken",
    thumbnail: "/hyderabadwali_shaadi_chicken.jpeg",
    videoUrl: "https://www.instagram.com/reel/DWfet3aDfKZ/embed/",
    videoType: "instagram",
    shortDescription: "A rich, aromatic Hyderabadi wedding-style chicken made with a nut and coconut paste, chilli sauces and slow-cooked until the oil separates.",
    prepTime: "20 mins",
    cookTime: "40 mins",
    totalTime: "1 hr (+ 2 hrs marinating)",
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "1 kg chicken, cut into medium pieces",
      "15 almonds",
      "15 cashews",
      "½ cup desiccated coconut",
      "250g yoghurt",
      "3 tbsp ginger garlic paste",
      "2 tsp black pepper powder",
      "2 tsp red chilli powder",
      "2 tsp garam masala",
      "½ tsp turmeric powder",
      "Juice of 1 lemon",
      "2 tbsp red chilli sauce",
      "2 tbsp green chilli sauce",
      "1 tbsp soy sauce",
      "1 large tomato, puréed",
      "4–5 green chillies, slit",
      "2 tbsp ghee",
      "2 large onions, fried",
      "Mint, chopped",
      "Cilantro, chopped",
      "1–2 tbsp heavy cream",
      "Oil, as needed",
      "Salt, to taste",
      "¼ tsp red food colour (optional)",
    ],
    method: [
      "Grind almonds, cashews and desiccated coconut with a little water or yoghurt into a smooth paste.",
      "Add the nut paste to the chicken along with all remaining ingredients: yoghurt, ginger garlic paste, black pepper, red chilli powder, garam masala, turmeric, lemon juice, red chilli sauce, green chilli sauce, soy sauce, tomato purée, green chillies, ghee, fried onions, mint, cilantro, food colour and salt.",
      "Mix thoroughly to coat every piece. Marinate for at least 2 hours, or overnight in the fridge.",
      "Heat oil in a large heavy-based pan. Add the marinated chicken and cook on medium-high heat for 5–7 minutes, stirring frequently.",
      "Cover and reduce to low heat. Cook for about 30 minutes until the chicken is completely tender and the oil visibly separates on the surface.",
      "Finish with heavy cream, stir gently and garnish with fresh cilantro. Serve immediately.",
    ],
    tips: [
      "The chilli sauces (red and green) are from Indian grocery stores — they add a distinct flavour you can't replicate otherwise.",
      "Oil separating is the sign the curry is cooked properly — don't shortcut this step.",
      "Serve with basmati rice, biryani or fresh naan.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["tandoori-chicken", "pepes-style-chicken", "miso-chicken-and-spinach-rice"],
    seoTitle: "Hyderabadwali Shaadi Chicken | Curated Recipes",
    seoDescription: "Rich Hyderabadi wedding-style chicken with a nut paste, chilli sauces and slow-cooked depth. Full written recipe.",
  },
  {
    id: "4",
    slug: "rajma-chawal-jar",
    title: "Rajma Chawal Jar",
    category: "Vegetarian",
    thumbnail: "/high_protein_kidney_beans_jar.jpeg",
    videoUrl: "https://www.instagram.com/reel/DXhCqJOCDbd/embed/",
    videoType: "instagram",
    shortDescription: "A layered high-protein rajma chawal jar with paneer, fresh veg, Greek yogurt and spices — 43g of protein at around 450 calories.",
    prepTime: "10 mins",
    cookTime: "10 mins",
    totalTime: "20 mins",
    servings: 1,
    difficulty: "Easy",
    ingredients: [
      "100g boiled rajma (kidney beans)",
      "100g cooked rice",
      "100g air-fried low-fat paneer",
      "Some onions, diced",
      "Some tomatoes, diced",
      "Some cucumber, diced",
      "100g 0% fat Greek yogurt",
      "Fresh coriander leaves",
      "1 tsp rajma masala",
      "Cumin powder, to taste",
      "Chilli flakes, to taste",
      "Salt and pepper, to taste",
      "Squeeze of lime",
    ],
    method: [
      "Air fry the paneer until golden on the outside, roughly 10 minutes at 180°C. Set aside.",
      "Season the rajma with rajma masala, cumin powder, chilli flakes, salt and pepper. Mix well.",
      "In a large jar or bowl, layer the cooked rice at the base.",
      "Add the seasoned rajma on top, followed by the air-fried paneer.",
      "Add the diced onions, tomatoes and cucumber.",
      "Spoon over the Greek yogurt.",
      "Squeeze over lime juice and garnish with fresh coriander leaves.",
      "Serve immediately or keep refrigerated for a meal prep lunch.",
    ],
    tips: [
      "This works brilliantly as meal prep — assemble everything except the yogurt and add that fresh when serving.",
      "Use canned kidney beans for speed — just rinse and season.",
      "The rajma masala is key for flavour — find it at any Indian grocery store.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["high-protein-paneer-jar", "broccoli-egg-tart", "high-protein-gochujang-tofu"],
    seoTitle: "Rajma Chawal Jar | Curated Recipes",
    seoDescription: "High-protein rajma chawal jar with paneer, Greek yogurt and fresh veg — 43g protein, 450 calories. Full written recipe.",
    calories: 457,
    protein: 43.5,
    carbs: 53.5,
    fats: 5.5,
    fibre: 7,
  },
  {
    id: "5",
    slug: "jerk-chicken-rice-and-peas",
    title: "Jerk Chicken, Rice & Peas",
    category: "Chicken",
    thumbnail: "/jerk_chicken_rice_peas.jpg",
    videoUrl: "https://www.instagram.com/reel/DXUr3Y3DCWO/embed/",
    videoType: "instagram",
    shortDescription: "Proper jerk chicken cooked low and slow, finished with extra marinade, served alongside coconut milk rice and peas.",
    prepTime: "20 mins",
    cookTime: "1 hr 5 mins",
    totalTime: "1 hr 25 mins",
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "— Jerk Chicken —",
      "Chicken pieces (thighs/drumsticks recommended)",
      "All-purpose seasoning",
      "Garlic powder",
      "Onion powder",
      "Paprika",
      "Ginger powder",
      "Honey",
      "Chopped garlic",
      "Green seasoning",
      "Jerk seasoning",
      "Browning sauce",
      "Jerk BBQ sauce",
      "Bell peppers, sliced",
      "Spring onion, chopped",
      "Fresh thyme",
      "— Rice & Peas —",
      "2 cans of red kidney beans",
      "2 spring onions, chopped",
      "All-purpose seasoning",
      "1 scotch bonnet (whole)",
      "3 cups of rice",
      "1½ cups of water",
      "Fresh thyme",
      "1 tbsp coconut oil",
      "1 can of coconut milk",
      "1 tsp butter",
    ],
    method: [
      "Combine all jerk chicken marinade ingredients — all-purpose, garlic powder, onion powder, paprika, ginger powder, honey, chopped garlic, green seasoning, jerk seasoning, browning, jerk BBQ sauce — with bell peppers, spring onion and thyme.",
      "Coat the chicken thoroughly in the marinade. Marinate for at least 2 hours or overnight.",
      "Bake the chicken at 200°C for 55 minutes until cooked through.",
      "Brush the leftover marinade over the cooked chicken and return to the oven (or air fryer) for a further 10 minutes until sticky and caramelised.",
      "For the rice and peas: add the coconut oil, spring onions, thyme, all-purpose seasoning and the whole scotch bonnet to a large pot. Stir briefly over medium heat.",
      "Add the kidney beans (with their liquid from one can), coconut milk and water. Bring to the boil.",
      "Boil for 15 minutes, then add the rice and butter. Stir, cover with a lid and cook on low for 20 minutes until the rice is fluffy and the liquid has absorbed.",
      "Remove the scotch bonnet before serving. Serve the jerk chicken over the rice and peas.",
    ],
    tips: [
      "Keep the scotch bonnet whole — it adds flavour without too much heat. For a spicier dish, pierce it.",
      "The second round of marinade glaze on the cooked chicken is what gives it that deep, sticky finish.",
      "Browning sauce is essential for the authentic dark colour — find it in Caribbean or world food aisles.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["tandoori-chicken", "pepes-style-chicken", "korean-style-chicken"],
    seoTitle: "Jerk Chicken, Rice & Peas | Curated Recipes",
    seoDescription: "Proper jerk chicken with coconut milk rice and peas. Full step-by-step written recipe from a viral Instagram reel.",
  },
  {
    id: "6",
    slug: "bang-bang-chicken-tenders",
    title: "Bang Bang Chicken Tenders",
    category: "Chicken",
    thumbnail: "/bang_bang_chicken_tenders.png",
    videoUrl: "https://www.instagram.com/reel/DRARXagDYqB/embed/",
    videoType: "instagram",
    shortDescription: "Crispy air-fryer chicken tenders coated in crushed cornflakes and dunked in a creamy bang bang sauce. Under 500 calories for 3 fillets.",
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalTime: "25 mins",
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "— Chicken —",
      "300g chicken tenders (roughly 6)",
      "1 egg, whisked",
      "30g plain flour",
      "50g cornflakes, crushed",
      "1 tsp garlic powder",
      "1 tsp onion powder",
      "Salt and pepper",
      "10 sprays cooking oil",
      "— Bang Bang Sauce —",
      "100g 0% fat Greek yogurt",
      "30g sweet chilli sauce",
      "1 tsp sriracha",
      "20g honey",
      "5g extra sweet chilli sauce (per tender, for smearing)",
    ],
    method: [
      "Season the chicken tenders with salt, pepper, garlic powder and onion powder.",
      "Set up a breading station with three separate bowls: whisked egg, plain flour and crushed cornflakes.",
      "Dip each tender into flour first, then egg, then crushed cornflakes — pressing gently so the coating sticks.",
      "Place the coated tenders in the air fryer basket. Spray with cooking oil.",
      "Air fry at 200°C for 15 minutes, flipping halfway, until golden and crispy.",
      "While the chicken cooks, mix together the Greek yogurt, sweet chilli sauce, sriracha and honey until smooth.",
      "When the tenders are done, smear extra sweet chilli sauce on each one, then dip into the bang bang sauce.",
    ],
    tips: [
      "Crush the cornflakes finely — they give a much crispier result than breadcrumbs.",
      "Don't skip the extra sweet chilli smear before dipping — it adds a sticky, jammy layer under the sauce.",
      "These reheat brilliantly in the air fryer at 180°C for 5 minutes.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["korean-popcorn-chicken", "korean-style-chicken", "pepes-style-chicken"],
    seoTitle: "Bang Bang Chicken Tenders | Curated Recipes",
    seoDescription: "Crispy air-fryer chicken tenders with a creamy bang bang sauce — 477 calories, 50g protein per 3 fillets. Full written recipe.",
    calories: 477,
    protein: 50,
    carbs: 58,
    fats: 5,
  },
  {
    id: "7",
    slug: "korean-style-chicken",
    title: "Korean Style Chicken",
    category: "Chicken",
    thumbnail: "/korean-fried-chicken-1-3.jpg",
    videoUrl: "https://www.instagram.com/reel/DT992x3jH-j/embed/",
    videoType: "instagram",
    shortDescription: "Crispy cornflour-coated chicken breast glazed in a sticky sweet-soy Korean sauce. Air-fried in 10 minutes.",
    prepTime: "5 mins",
    cookTime: "15 mins",
    totalTime: "20 mins",
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "— Chicken —",
      "600g chicken breast, sliced or cut into pieces",
      "50g cornflour",
      "Olive oil",
      "Salt and pepper",
      "— Sauce —",
      "50ml soy sauce",
      "Splash of water",
      "Honey, to taste",
      "Tomato purée, to taste",
    ],
    method: [
      "Cut the chicken breast into even pieces or strips. Season with salt and pepper.",
      "Toss in cornflour until each piece is evenly coated. Drizzle or spray with olive oil.",
      "Air fry at 200°C / 390°F for 10 minutes until crispy and cooked through.",
      "While the chicken cooks, combine soy sauce, a splash of water, honey and tomato purée in a small pan over medium heat. Stir and simmer for 2–3 minutes until the sauce thickens slightly.",
      "Toss the cooked chicken in the glaze until fully coated. Serve immediately.",
    ],
    tips: [
      "Make sure the cornflour coating is even and not too thick — light and even is best for crispiness.",
      "Adjust the honey and tomato purée to your taste: more honey for sweeter, more tomato for depth.",
      "Serve over rice with sesame seeds and spring onions for a complete meal.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["korean-popcorn-chicken", "bang-bang-chicken-tenders", "miso-chicken-and-spinach-rice"],
    seoTitle: "Korean Style Chicken | Curated Recipes",
    seoDescription: "Crispy air-fried chicken with a sticky sweet-soy Korean glaze. Quick, simple written recipe from a viral Instagram reel.",
  },
  {
    id: "8",
    slug: "protein-pesto-salad",
    title: "Protein Pesto Salad",
    category: "Chicken",
    thumbnail: "/pesto_pasta_salad.jpeg",
    videoUrl: "https://www.instagram.com/reel/DRwMcVIk7vQ/embed/",
    videoType: "instagram",
    shortDescription: "A creamy pesto pasta salad with Greek yogurt base, peri peri chicken, spinach and cherry tomatoes. High-protein and ready in minutes.",
    prepTime: "10 mins",
    cookTime: "10 mins",
    totalTime: "20 mins",
    servings: 1,
    difficulty: "Easy",
    ingredients: [
      "150g Greek yogurt",
      "20g pesto",
      "50g spinach",
      "30g onion, diced",
      "100g cherry tomatoes, halved",
      "50g high-protein pasta (raw weight)",
      "80g peri peri diced chicken (pre-cooked)",
    ],
    method: [
      "Cook the pasta according to packet instructions. Drain and allow to cool slightly.",
      "In a large bowl, mix together the Greek yogurt and pesto until smooth and combined.",
      "Add the spinach, diced onion and cherry tomatoes to the bowl.",
      "Add the cooked pasta and peri peri chicken.",
      "Toss everything together until fully coated in the creamy pesto dressing. Serve immediately or refrigerate for meal prep.",
    ],
    tips: [
      "High-protein pasta (made from chickpeas or lentils) significantly boosts the protein content of this dish.",
      "This keeps well in the fridge for up to 2 days — great for meal prep.",
      "Use any pre-cooked seasoned chicken if peri peri isn't available.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["rajma-chawal-jar", "high-protein-paneer-jar", "bang-bang-chicken-tenders"],
    seoTitle: "Protein Pesto Salad | Curated Recipes",
    seoDescription: "Creamy pesto pasta salad with Greek yogurt, peri peri chicken and fresh veg. A high-protein meal in 20 minutes.",
  },
  {
    id: "9",
    slug: "high-protein-paneer-jar",
    title: "High Protein Paneer Jar",
    category: "Vegetarian",
    thumbnail: "/high_protein_paneer_jar.jpeg",
    videoUrl: "https://www.instagram.com/reel/DRJwaYcD9SU/embed/",
    videoType: "instagram",
    shortDescription: "A refreshing, spiced paneer jar with crispy air-fried paneer, cucumber, sweetcorn, fresh veg and creamy yogurt. 44.5g protein per serve.",
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalTime: "25 mins",
    servings: 1,
    difficulty: "Easy",
    ingredients: [
      "150g low-fat paneer, torn into chunks",
      "50g cucumber, diced",
      "40g sweetcorn",
      "50g onions, diced",
      "50g tomatoes, diced",
      "Handful of lettuce",
      "100g low-fat yogurt",
      "Salt, to taste",
      "Black pepper, to taste",
      "Chilli flakes, to taste",
      "Cumin powder, to taste",
      "Squeeze of lime",
      "Fresh coriander leaves",
    ],
    method: [
      "Spray the paneer chunks with a little oil and air fry at 180°C for 12–15 minutes until golden and crispy on the outside.",
      "While the paneer cooks, dice the cucumber, onions and tomatoes.",
      "In a large jar or bowl, layer the lettuce at the base.",
      "Add the cucumber, sweetcorn, onions and tomatoes.",
      "Top with the crispy paneer.",
      "Spoon over the yogurt and season with salt, pepper, chilli flakes and cumin powder.",
      "Squeeze over lime juice and scatter fresh coriander on top. Mix before eating.",
    ],
    tips: [
      "Air-frying the paneer gives it a crispy exterior that holds up beautifully in the yogurt dressing.",
      "Mix everything just before eating so the lettuce stays crisp.",
      "Add a sprinkle of chaat masala for an extra punch of flavour.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["rajma-chawal-jar", "broccoli-egg-tart", "high-protein-gochujang-tofu"],
    seoTitle: "High Protein Paneer Jar | Curated Recipes",
    seoDescription: "Crispy air-fried paneer with fresh veg, spiced yogurt and lime — 44.5g protein, 358 calories. Full written recipe.",
    calories: 358,
    protein: 44.5,
    carbs: 17.2,
    fats: 8,
  },
  {
    id: "10",
    slug: "broccoli-egg-tart",
    title: "Broccoli Egg Tart",
    category: "Vegetarian",
    thumbnail: "/cheddar_broccoli_tart.jpg",
    videoUrl: "https://www.instagram.com/reel/DTQ2E79jZk_/embed/",
    videoType: "instagram",
    shortDescription: "A golden, crustless egg tart with smashed broccoli as the base, topped with peppers, sweetcorn, egg and melted mozzarella.",
    prepTime: "10 mins",
    cookTime: "25 mins",
    totalTime: "35 mins",
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "1 broccoli crown, cut into florets",
      "1 tbsp olive oil",
      "Salt, pepper, paprika and chilli flakes",
      "½ red pepper, chopped",
      "Large handful of sweetcorn",
      "3 eggs, whisked",
      "Handful of grated mozzarella",
    ],
    method: [
      "Preheat the oven to 180°C.",
      "Boil the broccoli florets until fork-tender, around 4–5 minutes. Drain well.",
      "Transfer the cooked broccoli to a greased or lined oven dish. Using the back of a mug, gently smash and flatten the broccoli to cover the base evenly.",
      "Drizzle with olive oil and season generously with salt, pepper, paprika and chilli flakes.",
      "Scatter the chopped red pepper and sweetcorn over the broccoli base.",
      "Pour the whisked eggs evenly over the top.",
      "Scatter the grated mozzarella over everything.",
      "Bake for 20–25 minutes until the egg is set and the cheese is golden and crispy on top.",
    ],
    tips: [
      "Drain the broccoli really well before smashing — excess water will make the tart soggy.",
      "Add any leftover veg you have: mushrooms, spinach or courgette all work well.",
      "This is great hot or cold and keeps well in the fridge for 2 days.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["rajma-chawal-jar", "high-protein-paneer-jar", "high-protein-gochujang-tofu"],
    seoTitle: "Broccoli Egg Tart | Curated Recipes",
    seoDescription: "Golden crustless egg tart with smashed broccoli base, peppers, sweetcorn and melted mozzarella. Full written recipe.",
  },
  {
    id: "11",
    slug: "miso-chicken-and-spinach-rice",
    title: "Miso Chicken & Spinach Rice",
    category: "Chicken",
    thumbnail: "/miso_chicken_spinach_rice.jpeg",
    videoUrl: "https://www.instagram.com/reel/DPf_v2ICERT/embed/",
    videoType: "instagram",
    shortDescription: "Charred miso and honey glazed chicken thighs served over vivid green spinach sushi rice, finished with an egg yolk and fresh chives.",
    prepTime: "15 mins",
    cookTime: "30 mins",
    totalTime: "45 mins",
    servings: 2,
    difficulty: "Medium",
    ingredients: [
      "— Chicken —",
      "400g boneless, skinless chicken thighs",
      "90g red miso",
      "40g honey",
      "20g soy sauce",
      "Juice of ½ lemon",
      "½ tsp MSG (optional)",
      "Salt and black pepper",
      "— Spinach Rice —",
      "100g sushi rice",
      "125ml water",
      "50g spinach",
      "1 garlic clove",
      "10g butter",
      "— To Serve —",
      "1–2 egg yolks",
      "Fresh chives, chopped",
      "Lemon wedges",
    ],
    method: [
      "Heat the grill to high.",
      "Add the spinach, butter, water and garlic clove to a blender. Blitz for about 1 minute until vivid, smooth and green.",
      "Rinse the sushi rice under cold water until it runs clear. Drain and add to a small saucepan with the spinach water.",
      "Bring to the boil, then cover with a tight-fitting lid, reduce to the lowest heat and cook for 12 minutes. Turn off the heat and leave to steam, lid on, for another 12 minutes. Do not lift the lid.",
      "In a bowl, whisk together the miso, honey, soy sauce, lemon juice, MSG (if using), a pinch of salt and black pepper.",
      "Slice each chicken thigh into three strips and toss through the miso marinade.",
      "Lay the chicken strips on a lined baking tray and spoon over any remaining sauce.",
      "Grill for 6–8 minutes until charred on the edges and cooked through.",
      "Spoon the spinach rice into bowls, top with the grilled chicken and spoon over any sauce from the tray.",
      "Finish each bowl with a raw egg yolk, chopped chives and a wedge of lemon.",
    ],
    tips: [
      "Red miso is saltier and deeper than white miso — don't substitute.",
      "The double-resting method (12 mins cook, 12 mins steam) gives perfectly fluffy, separate grains of sushi rice every time.",
      "The raw egg yolk is traditional and adds richness — mix it through the hot rice and it will gently cook from the heat.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["korean-style-chicken", "tandoori-chicken", "bang-bang-chicken-tenders"],
    seoTitle: "Miso Chicken & Spinach Rice | Curated Recipes",
    seoDescription: "Charred miso-glazed chicken thighs with vivid green spinach sushi rice and egg yolk. Full written recipe from Instagram.",
  },
  {
    id: "12",
    slug: "korean-popcorn-chicken",
    title: "High Protein Korean Popcorn Chicken",
    category: "Chicken",
    thumbnail: "/korean_popcorn_chicken.jpg",
    videoUrl: "https://www.instagram.com/reel/DMofIzbIVT3/embed/",
    videoType: "instagram",
    shortDescription: "Crispy air-fried popcorn chicken tossed in a sticky gochujang glaze, served over sweet sticky rice. 50g protein per meal.",
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalTime: "25 mins",
    servings: 2,
    difficulty: "Medium",
    ingredients: [
      "— Popcorn Chicken —",
      "800g chicken breast, cut into bite-sized pieces",
      "1 tbsp black pepper",
      "20ml soy sauce",
      "1 egg",
      "40g cornflour / cornstarch",
      "— Korean Glaze —",
      "60ml soy sauce",
      "80ml water",
      "2 tbsp low-calorie ketchup",
      "3 tbsp gochujang paste",
      "2 tbsp rice vinegar",
      "2 tbsp honey",
      "30g brown sugar (or brown stevia)",
      "— Sweet Sticky Rice —",
      "200g uncooked sticky rice",
      "3 tbsp rice vinegar",
      "1 tbsp sweetener",
      "Salt, to taste",
      "— Garnish —",
      "Spring onions (green parts), chopped",
      "Sesame seeds",
    ],
    method: [
      "Marinate the chicken in black pepper and soy sauce for 10 minutes. Add the egg and mix, then toss in cornflour until each piece is evenly coated.",
      "Air fry at 200°C for 10–12 minutes (or oven bake at 220°C for 15–20 minutes) until golden and crispy.",
      "For the glaze: combine soy sauce, water, ketchup, gochujang, rice vinegar, honey and brown sugar in a pan. Simmer for 3–4 minutes until slightly thickened.",
      "Cook the sticky rice according to packet instructions. Allow to cool for 10 minutes.",
      "Season the cooked rice with rice vinegar, sweetener and salt. Mix gently.",
      "Toss the crispy chicken in the Korean glaze until fully coated.",
      "Serve the glazed chicken over the sticky rice. Top with chopped spring onions and sesame seeds.",
    ],
    tips: [
      "Gochujang paste is now widely available in most supermarkets — it's the backbone of this glaze.",
      "Let the sticky rice cool slightly before adding the seasoning — it absorbs better and the texture improves.",
      "For extra crunch, double-coat the chicken in cornflour.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["korean-style-chicken", "bang-bang-chicken-tenders", "miso-chicken-and-spinach-rice"],
    seoTitle: "High Protein Korean Popcorn Chicken | Curated Recipes",
    seoDescription: "Crispy air-fried popcorn chicken in a sticky gochujang glaze with sweet sticky rice — 495 calories, 50g protein. Full recipe.",
    calories: 495,
    protein: 50,
    carbs: 68,
    fats: 3,
  },
  {
    id: "13",
    slug: "high-protein-gochujang-tofu",
    title: "High Protein Gochujang Tofu",
    category: "Vegetarian",
    thumbnail: "/gochujang-tofu.jpg",
    videoUrl: "https://www.instagram.com/reel/DEz9rXdMU73/embed/",
    videoType: "instagram",
    shortDescription: "Crispy air-fried tofu tossed in a spicy, sticky gochujang sauce with soy, sriracha mayo and ginger garlic. Ready in 25 minutes.",
    prepTime: "5 mins",
    cookTime: "20 mins",
    totalTime: "25 mins",
    servings: 1,
    difficulty: "Easy",
    ingredients: [
      "1 block (280g) firm tofu (Tofoo brand recommended)",
      "2 tbsp cornflour",
      "Oil spray",
      "¼ tsp salt",
      "¼ tsp black pepper",
      "¼ tsp paprika",
      "1 tbsp ginger garlic paste",
      "1 tbsp gochujang",
      "1 tbsp dark soy sauce",
      "1 tbsp sriracha mayo",
      "½ tsp brown sugar",
      "3 tbsp water",
      "Spring onions, to garnish",
    ],
    method: [
      "Tear the tofu into rough chunks — irregular edges get crispier than cuts.",
      "Toss the tofu with cornflour, salt, pepper and paprika. Spray generously with oil spray.",
      "Air fry at 180°C for 15 minutes, shaking halfway, until golden and crispy.",
      "Spray a pan lightly with oil. Add the ginger garlic paste, gochujang, dark soy sauce, sriracha mayo, brown sugar and water.",
      "Stir over medium heat until the sauce starts to bubble.",
      "Add the crispy tofu and toss until every piece is coated. If the sauce is too dry, add an extra tablespoon of water.",
      "Serve immediately topped with spring onions.",
    ],
    tips: [
      "Press the tofu before cooking to remove excess moisture — this is the key to getting it truly crispy.",
      "Tofoo brand is pre-pressed and extra firm, which is why it works so well here.",
      "Serve over rice or noodles to make it a complete meal.",
    ],
    creatorName: "Instagram Creator",
    creatorHandle: "@instagram",
    relatedRecipes: ["high-protein-paneer-jar", "rajma-chawal-jar", "broccoli-egg-tart"],
    seoTitle: "High Protein Gochujang Tofu | Curated Recipes",
    seoDescription: "Crispy air-fried tofu in a sticky gochujang sauce with soy and sriracha mayo. Easy high-protein vegetarian recipe.",
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return recipes.find((r) => r.slug === slug);
}

export function getRelatedRecipes(slugs: string[]): Recipe[] {
  return recipes.filter((r) => slugs.includes(r.slug)).slice(0, 3);
}
